name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # This triggers builds for Linux and Windows simultaneously
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true

      - name: Install cibuildwheel
        run: uv pip install cibuildwheel

      - name: Build wheels
        run: uv run cibuildwheel --output-dir wheelhouse
        # This command automatically detects your setup.py and 
        # compiles the C code for multiple Python versions.

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
